HOMEPAGE/urls.py
from django.urls import path
from . import views

app_name = 'HOMEPAGE'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery2/', views.gallery2, name='gallery2'),
    path('base/', views.base, name='base'),
    # path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi')
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

Story1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HOMEPAGE.urls')),
    path('', include('myspace.urls')),
]

myspace/urls.py
from django.urls import path
from . import views

app_name = 'myspace'

urlpatterns = [
    path('myspace/', views.myspace, name='space'),
    path('addSubject/', views.addSubject, name='addSubject'),
    path('listSubject/', views.listSubject, name='listSubject'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    # path('url-yang-diinginkan/', views.nama_fungsi, name='nama_fungsi')
    # path('profile/', views.profile, name='profile'),
    # dilanjutkan ...
]

HOMEPAGE/models.py
from django.db import models

# Create your models here.

myspace/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
    subject_name = models.CharField(max_length = 100)
    credits_amount = models.IntegerField()
    room = models.CharField(max_length = 100)
    lecturer = models.CharField(max_length = 100)
    year = models.CharField(max_length = 100)
    description = models.CharField(max_length = 1000, null = True)

    def __str__(self):
        return self.subject_name

myspace/forms.py
from django import forms 

class SubjectForm(forms.Form):
    subject_name = forms.CharField(
        label = "Subject name",
        widget = forms.TextInput(
            attrs = {
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Subject name',
            }
        )
    )

    credits_amount = forms.IntegerField(
        label = "Amount of credits",
        widget = forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6',
                'id' : 'fname',
                'placeholder' : 'Amount of credits',
            }
        )
    )

    room = forms.CharField(
        label = "Room", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Room',
            }
        )
    )

    lecturer = forms.CharField(
        label = "Lecturer name", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Lecturer name',
            }
        )
    )

    description = forms.CharField(
        label = "Subject description", 
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'cols' : '30',
                'rows' : '10',
                'id' : 'fname',
                'placeholder' : 'Subject description',
            }
        )
    )
    
    year = forms.CharField(
        label = "Semester", 
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
                'max_length : 100'
                'id' : 'fname',
                'placeholder' : 'Semester',
            }
        )
    )

HOMEPAGE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def gallery(request):
    return render(request, 'gallery.html')

def gallery2(request):
    return render(request, 'gallery2.html')

def base(request):
    return render(request, 'base.html')

myspace/views.py
from . import forms
from .models import Subject
from django.shortcuts import render, redirect

# Create your views here.
def myspace(request):
    return render(request, 'space.html')

def addSubject(request):
    subject_form = forms.SubjectForm()
    if request.method == 'POST':
        subject_form_input = forms.SubjectForm(request.POST)
        if subject_form_input.is_valid():
            data = subject_form_input.cleaned_data
            subject_input = Subject()
            subject_input.subject_name = data['subject_name']
            subject_input.credits_amount = data['credits_amount']
            subject_input.room = data['room']
            subject_input.lecturer = data['lecturer']
            subject_input.year = data['year']
            subject_input.description = data['description']
            subject_input.save()
            current_data = Subject.objects.all()

            return redirect('/listSubject')  
        else:
            current_data = Subject.objects.all()
            return render(request, 'add.html',{'form':subject_form, 'status':'failed','data':current_data})
    else:
        current_data = Subject.objects.all()
        return render(request, 'add.html',{'form':subject_form,'data':current_data})


def listSubject(request):
    data = Subject.objects.all()
    return render(request, 'list.html',{'listSubject' : data})

def delete(request, delete_id):
    try:
        deleted_subject = Subject.objects.get(pk = delete_id)
        deleted_subject.delete()
        return redirect('/listSubject')
    except:
        return redirect('/listSubject')

HOMEPAGE/templates/base.html
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/lib/Font-Awesome/css/fontawesome.min.css">
	<link rel="stylesheet" href="~/lib/Font-Awesome/css/regular.min.css">
	<link rel="stylesheet" href="~/lib/Font-Awesome/css/solid.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface">
	<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sacramento">

	{% load static %} 
	<link rel="stylesheet" href="{% static 'js/app.js' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
		
	<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">AS</a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav navbar-right">
                <li>
                <a href="{% url 'HOMEPAGE:index' %}">Home</a>
                </li>
				<li>
                <a href="{% url 'myspace:space' %}">My Space</a>
                </li>
                <li>
                <a href="{% url 'HOMEPAGE:gallery' %}">Gallery</a>
                </li>
				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Subject<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><a href="{% url 'myspace:addSubject' %}">Add Subject</a></li>
					<li><a href="{% url 'myspace:listSubject' %}">List Subject</a></li>
				</ul>
				</li>
            </ul>
            </nav>
        </div>
    </header>

    {% block content %}
    {% endblock %}

    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
		<br></br>
	</div>

	<div id="fh5co-started" class="fh5co-bg-dark-2">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2 id="space-font">Contact Me!</h2>
				</div>
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="https://twitter.com/flowerkels"><i class="fa fa-twitter"></i></a></li>
							<li><a href="https://instagram.com/ayukasnht"><i class="fa fa-instagram"></i></a></li>
							<li><a href="https://www.linkedin.com/in/ayuka-sonohata-66a47a19b/"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
			<br></br>
			<h5>© copyright 2020 Ayuka Sonohata.</h5>
		</div>
	</div>
	
	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
	</div>
	
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Easy PieChart -->
	<script src="{% static 'js/jquery.easypiechart.min.js' %}"></script>
	<!-- Google Map -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCefOgb1ZWqYtj7raVSmN4PL2WkTrc-KyA&sensor=false"></script>
	<script src="{% static 'js/google_map.js' %}"></script>
	
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

HOMEPAGE/templates/gallery.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
    {% block content %}
	<div id="fh5co-work" class="fh5co-bg-dark">
        <div id="fh5co-blog">
            <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section">Commitees</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/OH.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">November 2019</span>
                                <h3><a href="#">Open House Fasilkom UI 2019</a></h3>
                                <p>Acara untuk memberikan informasi tentang fasilkom UI ke anak SMA.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/sospro.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">October 2019</span>
                                <h3><a href="#">Social Project </a></h3>
                                <p>Acara sosial yang diadakan oleh Angkatan 2019 Fasilkom UI di Sekolah Master, Depok.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/syntax.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">September 2019</span>
                                <h3><a href="#">SYNTAX CSUI</a></h3>
                                <p>Acara gathering angkatan 2019 Fasilkom UI.</p>
                            </div> 
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/perak.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">February 2020</span>
                                <h3><a href="#">PERAK</a></h3>
                                <p>Acara Internal Fasilkom yang di dalamnya terdapat banyak rangkaian acara seperti lomba olahraga, seni, sampai Main Event.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/wisgan.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">January 2020</span>
                                <h3><a href="#">Wisuda Ganjil</a></h3>
                                <p>Acara Pelepasan Mahasiswa/i Fakultas Ilmu Komputer UI 2016.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/compfest.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">Maret 2020</span>
                                <h3><a href="#">COMPFEST 12</a></h3>
                                <p>Acara IT tahunan terbesar di Indonesia yang diselenggarakan oleh mahasiswa.</p>
                            </div> 
                        </div>
                    </div>
                </div>

                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section">Organizations</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/osis.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">October 2018</span>
                                <h3><a href="#">OSIS SMA</a></h3>
                                <p>Organisasi Siswa Intra Sekolah.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/lvc.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">May 2017</span>
                                <h3><a href="#">Lima Voice Club</a></h3>
                                <p>Ekstrakulikuler SMA yang bergerak dalam bidang vocal.</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/senbud.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">February 2020</span>
                                <h3><a href="#">BEM Fasilkom UI</a></h3>
                                <p>Departemen Seni dan Budaya.</p>
                            </div> 
                        </div>
                    </div>
                </div>

                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section">Hobbies</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="https://www.instagram.com/fiventidue/" class="blog-bg" style="background-image: url(/static/fv2.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">July 2018</span>
                                <h3><a href="https://www.instagram.com/fiventidue/">BUITENJOG Smansa Day</a></h3>
                                <p>Five Ventidue Band</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="https://www.instagram.com/fiventidue/" class="blog-bg" style="background-image: url(/static/fv.JPG);"></a>
                            <div class="blog-text">
                                <span class="posted_on">November 2018</span>
                                <h3><a href="https://www.instagram.com/fiventidue/">Recis Odyssey</a></h3>
                                <p>Five Ventidue Band</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="https://www.instagram.com/fiventidue/" class="blog-bg" style="background-image: url(/static/warna.JPG);"></a>
                            <div class="blog-text">
                                <span class="posted_on">March 2020</span>
                                <h3><a href="https://www.instagram.com/fiventidue/">Bir Bintang PERAK</a></h3>
                                <p>Warna-Warna Band</p>
                            </div> 
                        </div>
                    </div>
                </div>

                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section">Achievement</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/vg1.jpg);"></a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/vg.jpg);"></a>
                            <div class="blog-text">
                                <span class="posted_on">November 2019</span>
                                <h3><a href="#">Vocal Group UI Art War 2019</a></h3>
                                <p>Juara III</p>
                            </div> 
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="fh5co-blog animate-box">
                            <a href="#" class="blog-bg" style="background-image: url(/static/vg2.jpg);"></a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
	</div>

    {% endblock %}
</html>

myspace/templates/add.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
	{% block content %}	

	<div id="fh5co-started" class="fh5co-bg-dark">
		<div class="overlay"></div>
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2 id="h2-section">Add your subject here!</h2>
					<br></br>
					<br></br>
				</div>
				<div id="fh5co-consult" class="fh5co-bg-dark-2">
				<div class="video fh5co-video" style="background-image: url(/static/schedule.jpg);">
					<div class="overlay"></div>
				</div>
					
				<div class="choose animate-box">
					<h2>Subject Form</h2>
					<form action="#" method="post">
					{% csrf_token %}
						<div class="row form-group">
							<div class="col-md-12">
								{{ form.subject_name }}
							</div>
						</div>
						<div class="row form-group">
							<div class="col-md-12">
								{{ form.credits_amount }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.room }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.lecturer }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.year }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								{{ form.description }}
							</div>
						</div>
						
						<div class="form-group">
							<input type="submit" value="Add Subject" class="btn btn-primary">
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>


	{% endblock %}
</html>

myspace/templates/list.html
<!DOCTYPE HTML>

{% extends "base.html" %}

<html>
	{% block content %}	


    {% if listSubject.count == 0%}
    <div id="fh5co-work" class="fh5co-bg-dark">
		<div id="fh5co-blog">
		    <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section2">No subject added</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% else %}
	<div id="fh5co-work" class="fh5co-bg-dark">
		<div id="fh5co-blog">
		    <div class="container">
                <div class="row animate-box">
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <h2 id="h2-section2">Subject list</h2>
                    </div>
                    <table class="table">
                    <tr>
                        <th>Subject</th>
                        <th>Description</th>
                        <th>Credits</th>
                        <th>Lecturer</th>
                        <th>Room</th>
                        <th>Year</th>
                        <th>Remove</th>
                    </tr>

                    {% for subject in listSubject %}
                    <tr>
                        <td> {{subject.subject_name}} </td>
                        <td> {{subject.description}} </td>
                        <td> {{subject.credits_amount}} </td>
                        <td> {{subject.lecturer}} </td>
                        <td> {{subject.room}} </td>
                        <td> {{subject.year}} </td>
                        <td>
                            <a href = "{% url 'myspace:delete' delete_id=subject.pk %}">
                            <button class="btn btn-icon btn-danger"></button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </table>
                    <br></br>
                    <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                        <a href = "{% url 'myspace:addSubject' %}">
                        <input type="submit" value="ADD MORE SUBJECT" class="btn btn-success">
                        </a>
                    </div>
                </div>
			</div>
		</div>
	</div>

    {% endif %}

	{% endblock %}
</html>